In [11]:
import pandas as pd
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', '..')))

In [2]:
sentiment_train = pd.read_csv('../data/processed/sentiment_train.csv')
sentiment_test = pd.read_csv('../data/processed/sentiment_test.csv')

## Sentiment Dataset Analysis

In [3]:
sentiment_train.head()

                                            sentence  sentiment
0  with ya quot i d like a palm pre touchstone ch...          1
1  felt the earthquake this afternoon it seems to...          1
2          ruffles on shirts are like so in me likey          1
3  pretty bad night into a crappy morning fml if ...          0
4                             yeah what a clear view          1

In [4]:
sentiment_train["sentiment"].unique()

array([0, 1])

In [5]:
sentiment_train[sentiment_train["sentiment"]==1].head()

                                                 sentence  sentiment
767059                           i love u guys r the best          1
767060  im meeting up with one of my besties tonight c...          1
767061  thanks for the twitter add sunisa i got to mee...          1
767062  being sick can be really cheap when it hurts t...          1
767063                     he has that effect on everyone          1

In [6]:
sentiment_test.head()

                                            sentence  sentiment
0  i loooooooovvvvvveee my kindle not that the dx...          1
1  reading my kindle love it lee childs is good read          1
2  ok first assesment of the kindle it fucking rocks          1
3  you ll love your kindle i ve had mine for a fe...          1
4  fair enough but i have the kindle and i think ...          1

In [7]:
sentiment_test["sentiment"].unique()

array([1, 0])

In [8]:
sentiment_test[sentiment_test["sentiment"]==0].head()

                                             sentence  sentiment
6   fuck this economy i hate aig and their non loa...          0
10  i firmly believe that obama pelosi have zero d...          0
13  dear nike stop with the flywire that shit is a...          0
15  i was talking to this guy last night and he wa...          0
17  lebron is a beast but i m still cheering the a...          0

In [9]:
sentiment_train[sentiment_train["sentiment"]==0].shape

(767059, 2)

In [10]:
sentiment_train[sentiment_train["sentiment"]==1].shape

(756916, 2)

In [4]:
goemotions = pd.read_csv('../data/raw/goemotions_1.csv')

In [14]:
goemotions = goemotions.drop(columns=["id", "author", "subreddit", "created_utc", "rater_id", "example_very_unclear", "link_id", "parent_id"])

In [15]:
goemotions.head()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [15]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', '..')))
from utils import ALLOWED_EMOTIONS

In [16]:
goemotions_train = pd.read_csv("../data/processed/goemotions_train.csv")

In [17]:
def calculate_num_of_emotions(df):
    df = df.copy()
    num_of_emotions = {}

    for emotion in ALLOWED_EMOTIONS:
        num_of_emotions[emotion] = int(df[emotion].sum())

    return num_of_emotions

In [18]:
calculate_num_of_emotions(goemotions_train)

{'joy': 2075,
 'sadness': 1757,
 'anger': 2061,
 'fear': 829,
 'surprise': 1456,
 'neutral': 14753}